using UTSTalentHelpDesk.Models.Generic;
using UTSTalentHelpDesk.Models.Models;
namespace UTSTalentHelpDesk.Repositories.Infrastructure.Repositories
{
public class GenIncSalesIncentiveTargetSummaryHistoryRepository : GenericRepository<GenIncSalesIncentiveTargetSummaryHistory>, IGenIncSalesIncentiveTargetSummaryHistoryRepository
{
public GenIncSalesIncentiveTargetSummaryHistoryRepository(UTSTalentHelpDeskDBConnection dbContext) : base(dbContext){}
}
}
