using UTSTalentHelpDesk.Models.Generic;
using UTSTalentHelpDesk.Models.Models;
namespace UTSTalentHelpDesk.Repositories.Infrastructure.Repositories
{
public class PrgTempCertificationsMergePrgTalentCertificationRepository : GenericRepository<PrgTempCertificationsMergePrgTalentCertification>, IPrgTempCertificationsMergePrgTalentCertificationRepository
{
public PrgTempCertificationsMergePrgTalentCertificationRepository(UTSTalentHelpDeskDBConnection dbContext) : base(dbContext){}
}
}
