namespace UTSTalentHelpDesk.Models.Generic
{
    public interface IUnitOfWork : IDisposable
    {
        IUsrUserRepository usrUsers { get; }
        //ICustomExceptionRepository customExceptions { get; }
        //IGenAibasedHrtalentMatchMakingRepository genAibasedHrtalentMatchMakings { get; }
        //IGenAibasedHrtalentMatchMakingDetailRepository genAibasedHrtalentMatchMakingDetails { get; }
        //IGenAmAssignmentRuleHistoryRepository genAmAssignmentRuleHistorys { get; }
        //IGenAmnbdAssignmentEmailsendDetailRepository genAmnbdAssignmentEmailsendDetails { get; }
        //IGenBlogRepository genBlogs { get; }
        //IGenClientAmAssignmentRepository genClientAmAssignments { get; }
        //IGenClientAmAssignmentHistoryRepository genClientAmAssignmentHistorys { get; }
        //IGenClientCalendarEventRepository genClientCalendarEvents { get; }
        IGenClientHappinessSurveyRepository genClientHappinessSurveys { get; }
        IGenClientHappinessSurveyOptionRepository genClientHappinessSurveyOptions { get; }
        IGenClientHappinessSurveyQuestionRepository genClientHappinessSurveyQuestions { get; }
        //IGenClientPayOutAdditionalLineItemRepository genClientPayOutAdditionalLineItems { get; }
        IGenCompanyRepository genCompanys { get; }
        IGenCompanyContractDetailRepository genCompanyContractDetails { get; }
        IGenCompanyLeadTypeUserDetailRepository genCompanyLeadTypeUserDetails { get; } 
        //IGenCompanyLegalInfoRepository genCompanyLegalInfos { get; }
        //IGenCompanyUpdateRepository genCompanyUpdates { get; }
        //IGenCompanyWeightedAverageCriterionRepository genCompanyWeightedAverageCriterions { get; }
        IGenContactRepository genContacts { get; }
        //IGenContactGetHelpQuestionRepository genContactGetHelpQuestions { get; }
        //IGenContactHistoryRepository genContactHistorys { get; }
        //IGenContactInterviewFeedbackRepository genContactInterviewFeedbacks { get; }
        //IGenContactNotificationHistoryRepository genContactNotificationHistorys { get; }
        //IGenContactPendingActionRepository genContactPendingActions { get; }
        IGenContactPointofContactRepository genContactPointofContacts { get; }
        IGenContactTalentPriorityRepository genContactTalentPrioritys { get; }
        IGenDealRepository genDeals { get; }
        //IGenDealContactRepository genDealContacts { get; }
        //IGenDealTicketRepository genDealTickets { get; }
        //IGenDirectPlacementRepository genDirectPlacements { get; }
        //IGenEsalesAmApiResponseRepository genEsalesAmApiResponses { get; }
        //IGenFrontendClientRepository genFrontendClients { get; }
        //IGenHistoryRepository genHistorys { get; }
        //IGenHrnoteRepository genHrnotes { get; }
        //IGenHrnotesTagUserDetailRepository genHrnotesTagUserDetails { get; }
        //IGenHubSpotCompanyRepository genHubSpotCompanys { get; }
        //IGenHubSpotContactRepository genHubSpotContacts { get; }
        //IGenIncAmNrUserRoleDetailRepository genIncAmNrUserRoleDetails { get; }
        //IGenIncAmTalentDeployUserRoleDetailRepository genIncAmTalentDeployUserRoleDetails { get; }
        //IGenIncBaseSalUserRoleDetailRepository genIncBaseSalUserRoleDetails { get; }
        //IGenIncContractTalentUserRoleDetailRepository genIncContractTalentUserRoleDetails { get; }
        //IGenIncContractUserRoleDetailRepository genIncContractUserRoleDetails { get; }
        //IGenIncPlacementFeesTalentUserRoleDetailRepository genIncPlacementFeesTalentUserRoleDetails { get; }
        //IGenIncSalesIncentiveTargetDetailRepository genIncSalesIncentiveTargetDetails { get; }
        //IGenIncSalesIncentiveTargetSummaryRepository genIncSalesIncentiveTargetSummarys { get; }
        //IGenIncSalesIncentiveTargetSummaryHistoryRepository genIncSalesIncentiveTargetSummaryHistorys { get; }
        //IGenIncTargetAcheivedDetailRepository genIncTargetAcheivedDetails { get; }
        //IGenIncUserTargetRepository genIncUserTargets { get; }
        //IGenIncUserTargetsHistoryRepository genIncUserTargetsHistorys { get; }
        //IGenInterviewSlotsMasterRepository genInterviewSlotsMasters { get; }
        //IGenManagedTalentRepository genManagedTalents { get; }
        //IGenManagedTalentHistoryRepository genManagedTalentHistorys { get; }
        //IGenMenuMasterRepository genMenuMasters { get; }
        //IGenMenuRightRepository genMenuRights { get; }
        //IGenOnBoardClientContractDetailRepository genOnBoardClientContractDetails { get; }
        //IGenOnBoardClientDevicePolicyDetailRepository genOnBoardClientDevicePolicyDetails { get; }
        //IGenOnBoardClientInvoiceSummaryRepository genOnBoardClientInvoiceSummarys { get; }
        //IGenOnBoardClientLeavePolicyRepository genOnBoardClientLeavePolicys { get; }
        //IGenOnBoardClientTeamRepository genOnBoardClientTeams { get; }
        IGenOnBoardTalentRepository genOnBoardTalents { get; }
        //IGenOnBoardTalentsClientFeedbackRepository genOnBoardTalentsClientFeedbacks { get; }
        //IGenOnBoardTalentsLegalDetailRepository genOnBoardTalentsLegalDetails { get; }
        IGenOnBoardTalentsReplacementDetailRepository genOnBoardTalentsReplacementDetails { get; }
        //IGenOnlyDealIdRepository genOnlyDealIds { get; }
        //IGenPayoutInformationRepository genPayoutInformations { get; }
        //IGenPmsTalentRedirectUrlDetailRepository genPmsTalentRedirectUrlDetails { get; }
        //IGenPostalCodeswithDetailRepository genPostalCodeswithDetails { get; }
        IGenSalesHiringRequestRepository genSalesHiringRequests { get; }
        //IGenSalesHiringRequestDetailRepository genSalesHiringRequestDetails { get; }
        //IGenSalesHiringRequestDetailsHistoryRepository genSalesHiringRequestDetailsHistorys { get; }
        //IGenSalesHiringRequestHistoryRepository genSalesHiringRequestHistorys { get; }
        //IGenSalesHiringRequestInterviewerDetailRepository genSalesHiringRequestInterviewerDetails { get; }
        //IGenSalesHiringRequestPriorityRepository genSalesHiringRequestPrioritys { get; }
        //IGenSalesHiringRequestPriorityHistoryRepository genSalesHiringRequestPriorityHistorys { get; }
        IGenSalesHiringRequestSkillDetailRepository genSalesHiringRequestSkillDetails { get; }
        //IGenSalesHrJddumpRepository genSalesHrJddumps { get; }
        //IGenSalesHrJddumpSkillDetailRepository genSalesHrJddumpSkillDetails { get; }
        //IGenSalesHrTracceptedDetailRepository genSalesHrTracceptedDetails { get; }
        //IGenShortlistedTalentRepository genShortlistedTalents { get; }
        //IGenShortlistedTalentInterviewDetailRepository genShortlistedTalentInterviewDetails { get; }
        //IGenSocialMediaLoginDetailRepository genSocialMediaLoginDetails { get; }
        //IGenSystemConfigurationRepository genSystemConfigurations { get; }
        IGenTalentRepository genTalents { get; }
        //IGenTalentApplicationToolRepository genTalentApplicationTools { get; }
        //IGenTalentAssesmentScoreRepository genTalentAssesmentScores { get; }
        //IGenTalentAssesmentSkillScoreRepository genTalentAssesmentSkillScores { get; }
        //IGenTalentCertificationsDetailRepository genTalentCertificationsDetails { get; }
        //IGenTalentClientTeleRepository genTalentClientTeles { get; }
        //IGenTalentComfortableAreaDetailRepository genTalentComfortableAreaDetails { get; }
        //IGenTalentComfortableWorkingDetailRepository genTalentComfortableWorkingDetails { get; }
        //IGenTalentEducationDetailRepository genTalentEducationDetails { get; }
        //IGenTalentFinancialDetailRepository genTalentFinancialDetails { get; }
        //IGenTalentGetHelpQuestionRepository genTalentGetHelpQuestions { get; }
        //IGenTalentHistoryRepository genTalentHistorys { get; }
        //IGenTalentInterestDetailRepository genTalentInterestDetails { get; }
        //IGenTalentInterviewFeedbackRepository genTalentInterviewFeedbacks { get; }
        //IGenTalentKeyQualityDetailRepository genTalentKeyQualityDetails { get; }
        //IGenTalentLegalInfoRepository genTalentLegalInfos { get; }
        //IGenTalentNotificationHistoryRepository genTalentNotificationHistorys { get; }
        //IGenTalentPayOutAdditionalLineItemRepository genTalentPayOutAdditionalLineItems { get; }
        //IGenTalentPendingActionRepository genTalentPendingActions { get; }
        //IGenTalentPointofContactRepository genTalentPointofContacts { get; }
        //IGenTalentPreferableWorkingDetailRepository genTalentPreferableWorkingDetails { get; }
        //IGenTalentPrimarySkillDetailRepository genTalentPrimarySkillDetails { get; }
        //IGenTalentProfessionalExperienceRepository genTalentProfessionalExperiences { get; }
        //IGenTalentProjectDetailRepository genTalentProjectDetails { get; }
        //IGenTalentResumeDetailRepository genTalentResumeDetails { get; }
        //IGenTalentSecondarySkillDetailRepository genTalentSecondarySkillDetails { get; }
        //IGenTalentSelectedInterviewDetailRepository genTalentSelectedInterviewDetails { get; }
        //IGenTalentSelectedInterviewerDetailRepository genTalentSelectedInterviewerDetails { get; }
        //IGenTalentSelectedNextRoundInterviewDetailRepository genTalentSelectedNextRoundInterviewDetails { get; }
        //IGenTalentSelectedPostAcceptanceDetailRepository genTalentSelectedPostAcceptanceDetails { get; }
        //IGenTalentSelectedPostAcceptanceNotMatchDetailRepository genTalentSelectedPostAcceptanceNotMatchDetails { get; }
        //IGenTalentSelectionHistoryRepository genTalentSelectionHistorys { get; }
        //IGenTalentTestimonialOrFeedbackRepository genTalentTestimonialOrFeedbacks { get; }
        IGenTeamRepository genTeams { get; }
        //IGenTeamDistributionRepository genTeamDistributions { get; }
        //IGenTestimonialRepository genTestimonials { get; }
        //IGenTicketRepository genTickets { get; }
        //IGenUserHistoryRepository genUserHistorys { get; }
        //IGenUtsAssignmentHistoryRepository genUtsAssignmentHistorys { get; }
        //IGenUTSTalentHelpDeskRecordRepository genUTSTalentHelpDeskRecords { get; }
        //IGenUtsOnBoardLineItemRepository genUtsOnBoardLineItems { get; }
        //IHubSpotEventTypeRepository hubSpotEventTypes { get; }
        //IHubspotWebhookNotificationRepository hubspotWebhookNotifications { get; }
        IPrgActionFilterRepository prgActionFilters { get; }
        //IPrgAmAssignmentRuleRepository prgAmAssignmentRules { get; }
        //IPrgAmdealContactRepository prgAmdealContacts { get; }
        //IPrgApitimeZoneResponseRepository prgApitimeZoneResponses { get; }
        //IPrgBenchMarkRepository prgBenchMarks { get; }
        //IPrgClientEngagementModelRepository prgClientEngagementModels { get; }
        IPrgClientHappinessSurveyFeedbackOptionRepository prgClientHappinessSurveyFeedbackOptions { get; }
        IPrgClientHappinessSurveyFeedbackQuestionRepository prgClientHappinessSurveyFeedbackQuestions { get; }
        //IPrgClientInvoiceStatusRepository prgClientInvoiceStatuss { get; }
        //IPrgClientLegalDocumentTypeRepository prgClientLegalDocumentTypes { get; }
        //IPrgClientStageRepository prgClientStages { get; }
        //IPrgCompanyCurrentOpenPositionRepository prgCompanyCurrentOpenPositions { get; }
        //IPrgCompanyDomainRepository prgCompanyDomains { get; }
        //IPrgCompanySizeRepository prgCompanySizes { get; }
        //IPrgCompanyTargetGroupRepository prgCompanyTargetGroups { get; }
        //IPrgCompanyTypeofInterviewerRepository prgCompanyTypeofInterviewers { get; }
        //IPrgContactActionRepository prgContactActions { get; }
        //IPrgContactStatusRepository prgContactStatuss { get; }
        //IPrgContactTimeZoneRepository prgContactTimeZones { get; }
        IPrgCountryRegionRepository prgCountryRegions { get; }
        //IPrgCrmApiDetailRepository prgCrmApiDetails { get; }
        //IPrgCrmApiPartnerRepository prgCrmApiPartners { get; }
        //IPrgCrmApiTestsResponseRepository prgCrmApiTestsResponses { get; }
        //IPrgCurrencyExchangeRateRepository prgCurrencyExchangeRates { get; }
        //IPrgDealPipelineRepository prgDealPipelines { get; }
        IPrgDealStageRepository prgDealStages { get; }
        //IPrgDealStatusRepository prgDealStatuss { get; }
        //IPrgDealStatusIdpipelineStageIdRepository prgDealStatusIdpipelineStageIds { get; }
        IPrgDealTypeRepository prgDealTypes { get; }
        IPrgDepartmentRepository prgDepartments { get; }
        //IPrgEmploymentStatusRepository prgEmploymentStatuss { get; }
        //IPrgExtractedSkillsforJdparsingRepository prgExtractedSkillsforJdparsings { get; }
        IPrgGeoRepository prgGeos { get; }
        //IPrgHiringRequestRoleStatusRepository prgHiringRequestRoleStatuss { get; }
        IPrgHiringRequestStatusRepository prgHiringRequestStatuss { get; }
        //IPrgHistoryActionRepository prgHistoryActions { get; }
        //IPrgHowSoonClientWantTalentRepository prgHowSoonClientWantTalents { get; }
        //IPrgHrdeleteReasonRepository prgHrdeleteReasons { get; }
        //IPrgIncAmNrSlabRepository prgIncAmNrSlabs { get; }
        //IPrgIncAmSlabRepository prgIncAmSlabs { get; }
        //IPrgIncContractsSlabRepository prgIncContractsSlabs { get; }
        //IPrgIncPlacementFeesSlabRepository prgIncPlacementFeesSlabs { get; }
        //IPrgIncSalgoalSlabRepository prgIncSalgoalSlabs { get; }
        //IPrgInterviewStatusRepository prgInterviewStatuss { get; }
        //IPrgMatchMakingFactorRepository prgMatchMakingFactors { get; }
        //IPrgMatchMakingSubFactorRepository prgMatchMakingSubFactors { get; }
        IPrgModeOfWorkingRepository prgModeOfWorkings { get; }
        //IPrgOnBoardLegalKickOffStatusRepository prgOnBoardLegalKickOffStatuss { get; }
        //IPrgOnBoardPolicyDeviceMasterRepository prgOnBoardPolicyDeviceMasters { get; }
        //IPrgOrgLevelRepository prgOrgLevels { get; }
        //IPrgPartialEngagementTypeRepository prgPartialEngagementTypes { get; }
        IPrgPipelineRepository prgPipelines { get; }
        //IPrgPreOnBoardStatusRepository prgPreOnBoardStatuss { get; }
        //IPrgRateCardRepository prgRateCards { get; }
        //IPrgRequirementRepository prgRequirements { get; }
        //IPrgRolesAndResponsilbityRepository prgRolesAndResponsilbitys { get; }
        IPrgSkillRepository prgSkills { get; }
        //IPrgSkillCategoryRepository prgSkillCategorys { get; }
        //IPrgSkillRankRepository prgSkillRanks { get; }
        //IPrgSkillSourceRepository prgSkillSources { get; }
        //IPrgSkillsInAssesmentRepository prgSkillsInAssesments { get; }
        //IPrgSkillsRoleRepository prgSkillsRoles { get; }
        //IPrgSlatimeRepository prgSlatimes { get; }
        //IPrgSocialProviderRepository prgSocialProviders { get; }
        IPrgSummaryStagesForReportRepository prgSummaryStagesForReports { get; }
        //IPrgTalentAccountStatusRepository prgTalentAccountStatuss { get; }
        //IPrgTalentActionRepository prgTalentActions { get; }
        //IPrgTalentApplicationToolRepository prgTalentApplicationTools { get; }
        //IPrgTalentAssociatedWithUplerRepository prgTalentAssociatedWithUplers { get; }
        //IPrgTalentCategoryRepository prgTalentCategorys { get; }
        //IPrgTalentCertificationRepository prgTalentCertifications { get; }
        //IPrgTalentComfortableAreaRepository prgTalentComfortableAreas { get; }
        //IPrgTalentComfortableWorkingRepository prgTalentComfortableWorkings { get; }
        //IPrgTalentCommunicationSkillRepository prgTalentCommunicationSkills { get; }
        //IPrgTalentInterestRepository prgTalentInterests { get; }
        //IPrgTalentJoinningRepository prgTalentJoinnings { get; }
        //IPrgTalentKeyQualityRepository prgTalentKeyQualitys { get; }
        //IPrgTalentLegalDocumentTypeRepository prgTalentLegalDocumentTypes { get; }
        //IPrgTalentPayoutStatusRepository prgTalentPayoutStatuss { get; }
        //IPrgTalentPreferableWorkingRepository prgTalentPreferableWorkings { get; }
        //IPrgTalentPrimarySkillRepository prgTalentPrimarySkills { get; }
        //IPrgTalentRejectReasonRepository prgTalentRejectReasons { get; }
        IPrgTalentRoleRepository prgTalentRoles { get; }
        //IPrgTalentRoleCategoryRepository prgTalentRoleCategorys { get; }
        //IPrgTalentRoleTemplateRepository prgTalentRoleTemplates { get; }
        //IPrgTalentSkillBenchMarkRepository prgTalentSkillBenchMarks { get; }
        //IPrgTalentStatusRepository prgTalentStatuss { get; }
        //IPrgTalentStatusAfterClientSelectionRepository prgTalentStatusAfterClientSelections { get; }
        //IPrgTalentTimeZoneRepository prgTalentTimeZones { get; }
        //IPrgTalentTypeRepository prgTalentTypes { get; }
        //IPrgTempApplicationToolRepository prgTempApplicationTools { get; }
        //IPrgTempApplicationToolsMergePrgTalentApplicationToolRepository prgTempApplicationToolsMergePrgTalentApplicationTools { get; }
        //IPrgTempCertificationRepository prgTempCertifications { get; }
        //IPrgTempCertificationsMergePrgTalentCertificationRepository prgTempCertificationsMergePrgTalentCertifications { get; }
        //IPrgTempInterestRepository prgTempInterests { get; }
        //IPrgTempInterestMergePrgTalentInterestRepository prgTempInterestMergePrgTalentInterests { get; }
        IPrgTempSkillRepository prgTempSkills { get; }
        //IPrgTempSkillsMergePrgSkillRepository prgTempSkillsMergePrgSkills { get; }
        //IPrgTicketCategoryRepository prgTicketCategorys { get; }
        //IPrgTicketStatusRepository prgTicketStatuss { get; }
        //IPrgTicketTechnicalJustificationRepository prgTicketTechnicalJustifications { get; }
        //IPrgTimeZoneRepository prgTimeZones { get; }
        //IPrgTimeZoneCostPreferenceRepository prgTimeZoneCostPreferences { get; }
        //IPrgTimeZonePreferenceRepository prgTimeZonePreferences { get; }
        //ISkillRole1Repository skillRole1s { get; }
        //IUsrUserGeoDetailRepository usrUserGeoDetails { get; }
        IUsrUserHierarchyRepository usrUserHierarchys { get; }
        //IUsrUserPriorityCountLogRepository usrUserPriorityCountLogs { get; }
        IUsrUserRoleRepository usrUserRoles { get; }
        IUsrUserRoleDetailRepository usrUserRoleDetails { get; }
        //IUsrUserTeamRepository usrUserTeams { get; }
        IUsrUserTypeRepository usrUserTypes { get; }
        IUsrUserTypeAndRoleDetailRepository usrUserTypeAndRoleDetails { get; }
        IStoreAPIUrlRepository storeAPIUrl { get; }
        int Save();
    }
}
